name: BBC
favicon: null
layout_spectrum: 0.6077849247958511
typography_spectrum: 0.3361911417450756
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5221979462075979
  lightness: 0.11111369356513023
  saturation: 0.26302900025621057
  rhythmicContrast: 0.20448849629610777
purpose: []
